language: ruby
script: bundle exec rake spec
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
gemfile:
  - gemfiles/Gemfile-sinatra
  - gemfiles/Gemfile-rails.3.0.x
  - gemfiles/Gemfile-rails.3.1.x
  - Gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile-rails.3.0.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile-rails.3.1.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.3.0.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.3.1.x
